## Global configurations

global:
  tags:
    service: "opensearch-service"
    Name: "opensearch"
    Environment: "sandbox"
    Owner: "backend-team"
    engineering-org: "backend"

opensearch_configs:
  opensearch_cluster_0:
    opensearch_domain_name: "osearch-0"
    opensearch_is_t2_or_t3_instance_type: true
    opensearch_instance_type: "t3.small.search"
    opensearch_data_node_instance_count: 1
    opensearch_dedicated_master_enabled: false
    
    opensearch_encrypt_at_rest: true
    opensearch_engine_version: "OpenSearch_2.13"
    opensearch_software_update_options: true
    kms_key_id_arn: "arn:aws:kms:us-east-1:654654381413:key/7b9c80e1-7f50-4c7f-bf5f-68e21274069e"
    subnet_ids: ["subnet-040f2439f45a55bbd"]
    #security_group_id: "sg-0b8139757fe1279b0"
    opensearch_ebs_configurations:
      volume_type: "gp2"
      volume_size: 20
      iops: 3000
      throughput: 125
      ebs_enabled: true

    opensearch_security_group_ingress_rule_name: "opensearch-0-security-group-ingress-rule"
    vpc_id: "vpc-09c66f534c904ef58"
    ingress_with_cidr_blocks: "10.100.0.0/16"
    opensearch_security_group_egress_rules: ["all-all"]
    vpc_cidr_block: "10.100.0.0/16"
   


















# global:
#   tags:
#     service: "eb-backend"
#     Name: "eb-backend"
#     Environment: "sandbox"
#     Owner: "backend-team"
#     engineering-org: "backend"
    
# opensearch:
#   # Domain configuration
#   advanced_options:
#     rest.action.multi.allow_explicit_index: "true"

#   advanced_security_options:
#     enabled: false
#     anonymous_auth_enabled: true
#     internal_user_database_enabled: true
#     master_user_options:
#       master_user_name: "opensearch-user"
#       master_user_password: "OpenSearchPassword@2024"  # Replace with a secure password

#   auto_tune_options:
#     desired_state: "DISABLED"  # Or "ENABLED" based on your t2/t3 instance type
#     maintenance_schedule:
#       - start_at: "2028-05-13T07:44:12Z"
#         cron_expression_for_recurrence: "cron(0 0 ? * 1 *)"
#         duration:
#           value: "2"
#           unit: "HOURS"
#     rollback_on_disable: "NO_ROLLBACK"

#   cluster_config:
#     instance_count: 1  # Number of instances
#     dedicated_master_enabled: false
#     instance_type: "t3.small.search"  # Example instance type
#     zone_awareness_enabled: false

#   domain_endpoint_options:
#     enforce_https: true
#     tls_security_policy: "Policy-Min-TLS-1-2-2019-07"

#   domain_name: "your-region-your-environment-osearch-0"  # Replace with your domain name

#   ebs_options:
#     ebs_enabled: true
#     iops: 3000
#     throughput: 125
#     volume_type: "gp3"
#     volume_size: 20

#   encrypt_at_rest:
#     enabled: true
#     kms_key_id_arn: "arn:aws:kms:us-east-1:654654381413:key/3e2c3940-31a9-42b5-bab4-6ce240ca554a"  # Replace with your KMS key ARN

#   engine_version: "OpenSearch_2.13"

#   log_publishing_options:
#     - log_type: "INDEX_SLOW_LOGS"
#       enabled: true
#       cloudwatch_log_group_arn: "arn:aws:logs:us-east-1:654654381413:log-group:/aws/codebuild/code_crunch_codebuild_project:*"
#     - log_type: "SEARCH_SLOW_LOGS"
#       enabled: true
#       cloudwatch_log_group_arn: "arn:aws:logs:us-east-1:654654381413:log-group:/aws/codebuild/code_crunch_codebuild_project:*"
#     - log_type: "ES_APPLICATION_LOGS"
#       enabled: true
#       cloudwatch_log_group_arn: "arn:aws:logs:us-east-1:654654381413:log-group:/aws/codebuild/code_crunch_codebuild_project:*"
#     - log_type: "AUDIT_LOGS"
#       enabled: false
#       cloudwatch_log_group_arn: "arn:aws:logs:us-east-1:654654381413:log-group:/aws/codebuild/code_crunch_codebuild_project:*"

#   ip_address_type: "ipv4"

#   node_to_node_encryption:
#     enabled: true

#   software_update_options:
#     auto_software_update_enabled: true

#   vpc_options:
#     subnet_ids:
#       - "subnet-0e74ba71842be5b62"  # Example private subnet ID
#     security_group_ids:
#       - "sg-0ea3fdf388f5c8601"  # Example security group ID

#   create_security_group: false
#   create_access_policy: false
#   access_policy_statements:
#     - effect: "Allow"
#       principal: "*"
#       actions:
#         - "es:*"
#       resource:
#       #  - "arn:aws:es:your-region:your-account-id:domain/your-domain-name/*"

#   tags:
#     sdlc: "rnd"
#     environment_name: "sandbox"
#     is_prod: "false"

# opensearch_security_group:
#   name: "your-region-your-environment-osearch-0-security-group"
#   description: "Security group used by OpenSearch"
#   vpc_id: "vpc-0d4dff948f2a7a05c"  # vpc id of sandbox environment vpc module one
#   egress_rules:
#     - "all-all"
#   ingress_with_cidr_blocks:
#     - rule: "elasticsearch-rest-tcp"
#       cidr_blocks: "10.100.0.0/16"
#       name: "your-region-your-environment-opensearch-0-security-group-ingress-rule-1"
#       description: "OpenSearch security group 1"
#     - rule: "elasticsearch-java-tcp"
#       cidr_blocks: "10.100.0.0/16"
#       name: "your-region-your-environment-opensearch-0-security-group-ingress-rule-2"
#       description: "OpenSearch security group 2"

#   tags:
#     sdlc: "rnd"
#     environment_name: "sandbox"
#     is_prod: "false"
#     customer_critical: "false"


