
name: CI-Pipeline

permissions:
  contents: read
  issues: write
  id-token: write

env:
  tf_version: '1.9.4'
  tg_version: '0.66.3'
  CURRENT_REPO: 'current-repo'
  TERRAFORM_MODULE_REPO: 'terraform-module-repo'

on:
  push:
    branches:
      - "main"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:

    - name: Clone this repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: ${{ env.CURRENT_REPO }}

    - name: Get modified files for merged commit only
      id: vars
      if: ${{ (github.event_name == 'push') }}
    # This command for git diff works for merged commit only
      run: |
        # git rev-parse HEAD
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }}^1  ${{ github.sha }}
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }}^1  ${{ github.sha }} >> changed_files.txt        
        cat changed_files.txt
        ls -alh .
      working-directory: ${{ env.CURRENT_REPO }}        

    #Doc -- https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::127214154743:role/assume-role-credentials
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1

    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/${{ env.tf_version }}/terraform_${{ env.tf_version }}_linux_amd64.zip
        unzip terraform_${{ env.tf_version }}_linux_amd64.zip
        chmod +x terraform
        sudo mv terraform /usr/local/bin/terraform    


    - name: Install Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.66.8/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: Apply Terraform for CI pipeline
      run: |
        declare -A set
        while IFS= read -r changed_file; do
          echo $changed_file
          arrChangedFile=(${changed_file//// })
          echo "${arrChangedFile[@]}"

          if [[ "${arrChangedFile[0]}" == "infrastructure" ]]; then
              echo "Start Terragrunt init and apply"
              dir_path=$(dirname "$changed_file")
              echo "Directory path: $dir_path"
              echo "terragrunt init --terragrunt-working-dir $dir_path"
              terragrunt init --terragrunt-working-dir $dir_path              
              echo "terragrunt --terragrunt-non-interactive apply --terragrunt-working-dir $dir_path -auto-approve"
              terragrunt --terragrunt-non-interactive apply --terragrunt-working-dir $dir_path -auto-approve

          else
              echo "Changed file not in path infrastructure/"
          fi
        done < changed_files.txt

      working-directory: ${{ env.CURRENT_REPO }}

    - name: Apply Terraform based on manual deoploy
      working-directory: ${{ env.CURRENT_REPO }}
      if: ${{ (github.event_name == 'workflow_dispatch') && (env.SKIP_WORKFLOW != 'true') }}
      run: |

        if [[ ${{ inputs.folder }} == "*" ]]; then # apply on all folder/modules
          declare -A set
          dir_path="infrastructure/${{ inputs.environment }}"
          for target_folder in "$dir_path"/*; do
            if [[ -d "$target_folder" ]]; then
              echo "$target_folder"
              terragrunt init --terragrunt-working-dir $target_folder
              terragrunt --terragrunt-non-interactive apply --terragrunt-working-dir $target_folder -auto-approve
            fi
          done
          echo "$folder"
          terragrunt init --terragrunt-working-dir $folder
          terragrunt --terragrunt-non-interactive apply --terragrunt-working-dir $folder -auto-approve
        else
          # apply on the specific module/nested folder 
          target_folder="infrastructure/${{ inputs.environment }}/${{ inputs.folder }}"
          terragrunt init --terragrunt-working-dir $target_folder
          terragrunt --terragrunt-non-interactive apply --terragrunt-working-dir $target_folder -auto-approve
        fi



